name: Continuous Deployment to AWS S3 and CloudFront when merge main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: NPM 패키지를 설치합니다.
        run: npm ci

      - name: 프로젝트를 빌드합니다.
        run: npm run build

      - name: S3 버킷에 배포합니다.
        run: |
          aws s3 sync ./out s3://${{ secrets.AWS_S3_BUCKET }} --delete

      - name: CloudFront 캐시를 무효화합니다.
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID  }} --paths "/*"
